### ISSUE TITLE
Change creditcard

### ISSUE THREAD

**Issue by pigmentGit** [PayEx/PayEx.WooCommerce#21]
**Issue**
We have a store and use Payex and Woocomerce. 
We can´t add function for remove, add, change creditcard. 
Is this function supported by your plugin?

**URL**
http://mybloodybox.se/

**Plugins**
WooCommerce PayEx Payments Gateway. Version 2.0.1

**Comment by aait** [comment]
It should work since this commit https://github.com/PayEx/PayEx.WooCommerce/pull/17
Note that you need an agreement with PayEx regarding "Autopay".
