### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by sjobidoo** [PayEx/PayEx.WooCommerce#25]
Using this plugin together with WooCommerce 2.6.2 gives an error on attempting to checkout:
`SyntaxError: Unexpected token < in JSON at position 0`

**Comment by asbjornu** [comment]
Sounds like HTML instead of JSON being returned from the server. Which other plugins have you installed?

**Comment by sjobidoo** [comment]
We currently have the following plugins active which are related to WooCommerce:

WooCommerce Customer/Order CSV Export
WooCommerce Colors
WooCommerce Checkout Field Editor
WooCommerce Email Customer Address
WooCommerce - Autocomplete Orders
WooCommerce Print Invoice/Packing list
WooCommerce Subscriptions

In the developer console og Chrome, the following is output: 
`Unable to fix malformed JSON` - checkout.js:381

**Comment by aait** [comment]
We have just performed a successful checkout with PayEx cardpayment in a vanilla Woo 2.6.2. Could we have a look at your system? Please contact us at info@aait.se
