### ISSUE TITLE
Address fields locks after GetAddressByPayment method is used

### ISSUE THREAD

**Issue by pxjoachim** [PayEx/PayEx.WooCommerce#40]
When you use GetAddressByPayment method to fetch address from SSN+Postal Code, all fields (Name, Address etc) lock and cannot be changed, even if the customer chooses other payments than PayEx Faktura (Financing).

Is it meant to be this way?

**Comment by aait** [comment]
Fixed #3da91053159120a307952aade7f5ee0ffdb4ae74
