### ISSUE TITLE
&-charachter in product name breaks FinancingInvoice Orderlines

### ISSUE THREAD

**Issue by PayExBent** [PayEx/PayEx.WooCommerce#41]
If merchant has products that contain "&" character, this will cause problems when PayEx Faktura (Financing Invoice) or PayEx Delbetala (Financing Credit Account) is used.

The "&" character seems to be added to the Product element in the XML without modification, escaping XML unintentionally. This causes the Product element to be empty, which does not validate when the XML is sent to PayEx.

Example of a orderline where the product name contained &-character:
`	<OrderLine>
		<Product/>
		<Qty>1</Qty>
		<UnitPrice>183.2</UnitPrice>
		<VatRate>25</VatRate>
		<VatAmount>45.8</VatAmount>
		<Amount>229</Amount>
	</OrderLine>`

A possible fix is to validate the product name before adding it to the XML, replacing `&` with `&amp;`

**Comment by aait** [comment]
Fixed #20
