### ISSUE TITLE
Failed to create agreement reference

### ISSUE THREAD

**Issue by dominykasgel** [PayEx/PayEx.WooCommerce#42]
I'm experiencing "Failed to create agreement reference". Account number, encryption key and callback url are set. All data from test-secure.payex.com. Anyone know what the problem is?

**Comment by aait** [comment]
Please check with support.ecom@payex.com and see if they have setup autopay properties for your account http://www.payexpim.com/extended-functionality/autopay-recurring-one-click-payments/

**Comment by dominykasgel** [comment]
Thanks! Closing.
