### ISSUE TITLE
Compatibility with WooCommerce 2.6 and WooCommerce Subscriptions 2.1

### ISSUE THREAD

**Issue by samppis** [PayEx/PayEx.WooCommerce#49]
After updating WooCommerce to 2.6.14 and Subscriptions to 2.1.3 we can no longer add/change cards for subscriptions under "My Account". Previously that worked just fine. Any thoughts?

**Comment by aait** [comment]
Whick version of WC and WCS was before?

**Comment by samppis** [comment]
Previously we had WC 2.5.5 and WCS 2.0.12

**Comment by aait** [comment]
And which version of payment plugin was before?

**Comment by samppis** [comment]
We had version 2.0.2 of WooCommerce PayEx Payments Gateway

**Comment by aait** [comment]
We cannot duplicate this problem. Please contact us at info@aait.se so we can proceed.

**Comment by aait** [comment]
Cant reproduce.
