### ISSUE TITLE
Orderlines round bug

### ISSUE THREAD

**Issue by vietzon** [PayEx/PayEx.WooCommerce#50]
Hejsan

It seems the plugin cannot rounding prices. Here is a image

https://www.evernote.com/l/AL_LVsbtNKVJGZn5cd-q5AOlIUzn9BdDA2UB/image.png

I use Faktura. The total price showed 138 as total (with rounding up). In payex admin i can see 138 too. But when i tried to mark as "Completed", suppose to send the invoice to customers, it failed to capture because 20 öre was missing...

Mvh
Daknight Team

**Comment by aait** [comment]
Hejsan,

Do you have 2 digits set in the currency settings for Woo? If not, try with that 
![image](https://cloud.githubusercontent.com/assets/6286270/23258015/9a305cc6-f9c6-11e6-90d1-429592483941.png)

**Comment by aait** [comment]
Merchant reports that above https://github.com/PayEx/PayEx.WooCommerce/issues/50#issuecomment-281972062 solved the problem

**Comment by vietzon** [comment]
Tack, det var nog det som strulade
