### ISSUE TITLE
Should order mark as processing if use PayEx Financing?

### ISSUE THREAD

**Issue by oaigudmundsson** [PayEx/PayEx.WooCommerce#51]
Hejsan

I would why you don't mark the order as "processing" when use PayEx Financing (aka. Faktura) ?

Right now, the order status is "Mottagen, invänta betalning", which is misleading. It should be "Processing", imo. Because as shop owner, you'll send the package, then mark "Färdigbehandlad". At that momemt, this plugin will tell payex to send the invoice. 

What do you think?

Mvh
Oai G

**Comment by aait** [comment]
Under discussion to make an option with a different orderflow, will let you know.

**Comment by aait** [comment]
@vietzon Hi, WooCommerce have reserved order statues. We are use "on-hold" and "processing" for authorized (or pending) and captured payments. You can change order status from "processing" to "completed" to mark order as shipped.
