### ISSUE TITLE
Problem with renewals over 1000,- when used in WooCommerce+WooCommer Subscriptions

### ISSUE THREAD

**Issue by sjobidoo** [PayEx/PayEx.WooCommerce#54]
Not sure where the error might be. But whenever a order exceeds 1000,- NOK, the initial order is successfull, payment is completed and setup as a renewal payment. But when the renewal order is created it fails with the following error in WooCommerce:

> Failed to charge «kr 1199» from Credit Card «**********». PayEx error: Agreement_PriceToHigh (Price 1199 is larger than agreement amount 1000.0000). Ordrestatus endret fra Awaiting payment til Failed.

Inside the Payex admin console, I can see that the initial transaction has been completed with the amount set: 1 199,00 NOK and Recurring = true.

Could there be any issue related to malformed amount in some way here in regards to spacing, decimals or similar?

**Comment by aait** [comment]
Please check this setting under woocommerce->settings->checkout-> PayEx Payments
![image](https://cloud.githubusercontent.com/assets/6286270/24774680/268e91d2-1b1a-11e7-875c-0dcf111088a6.png)
