### ISSUE TITLE
Transaction authorized not sending any e-mail notifications

### ISSUE THREAD

**Issue by folofse** [PayEx/PayEx.WooCommerce#58]
When a customer uses Payex Financing (invoice) to pay their orders we not receiving any notification email that tells us that the order is activated. Because of this we have missed out orders and the customer have cancelled their orders and gone to other stores.

**Comment by olegisk** [comment]
Sorry, i can't reproduce this bug: mail sending working well. See screenshot. Please check server configuration and make sure that outcoming mails are working.
![223](https://user-images.githubusercontent.com/871275/31122914-9af3dcd0-a85f-11e7-90cc-7fa4a519e7a2.png)

**Comment by folofse** [comment]
Thank you for your reply, I will check to see if any action-hook in the theme are causing this or if its something on the server side. I will be back to you.

**Comment by folofse** [comment]
I found that the email should be sent according to the mail-log on the server. So I guess it gets stuck somewhere. It might be some information or email-header that causes the problem.

**Comment by folofse** [comment]
I guess woocommerce is not sending order on hold out of the box to the admin, only the customer, so theres not any problem with the plugin.
