### ISSUE TITLE
No MobilePay logo

### ISSUE THREAD

**Issue by pxjoachim** [PayEx/PayEx.WooCommerce#59]
There is no MobilePay logo (mobilepay_online.png) in the wordpress\wp-content\plugins\PayEx.WooCommerce-master\assets\images as far as I can see. At the checkout I get this (same for another customer):

![mobilepaylogo](https://user-images.githubusercontent.com/16459824/26877123-2e4761b6-4b89-11e7-976d-750af825b673.JPG)

I suggest using this one https://mobilepay.dk/SiteCollectionImages/MobilePay-Universe-2/Materiale/Logoer/MobilePay_Logo.png or whichever works best: https://mobilepay.dk/da-dk/materialer/Pages/materialer.aspx#Logoer.

**Comment by olegisk** [comment]
Icon has been addded in this commit https://github.com/PayEx/PayEx.WooCommerce/commit/3c9511dd63ae1dcbb33594757846d0a9fd37c479
It seem somebody use old version
