### ISSUE TITLE
Problem with MasterPass

### ISSUE THREAD

**Issue by olegisk** [PayEx/PayEx.WooCommerce#61]
I'm discovered problem with MasterPass: ValidationError_Generic (Please enter a valid authorized client ID for the requested service. ERROR CODE 1000).
See screenshot.
![checkout wooshop](https://user-images.githubusercontent.com/871275/31927876-b74fce58-b8b7-11e7-8a1c-cae9fadc707e.png)

**Comment by olegisk** [comment]
@asbjornu Do you know reason of problem?

**Comment by erikhusemoen** [comment]
Vi er forsinket med fornyelse av sertifiseringsnøkler til Masterpass. Produksjonsnøkkelen fungerer fortsatt, men test har utgått. Årsaken er at mastercard har lansert ny developer site, og våre nøkler ble laget i det gamle. I migreringen til ny site så er våre eksisterende nøkler "forsvunnet".

Det er kommet inn ett forslag fra mastercard til løsning på dette, som vi forsøker å implementere nå i løpet av de nærmeste dagene. Beklager problemet dette medfører.
