### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by saumoor** [PayEx/PayEx.WooCommerce#69]
Customer is getting the following errormessage in all orders:
"Fatal error: Call to a member function get() on null in /home2/stowaway/public_html/wp-content/plugins/PayEx.WooCommerce-master/includes/class-wc-gateway-payex-masterpass.php on line 545" 

Error message is causing related orders to not being shown. 
Contact support.ecom@payex.com if you need login details to customers WP backend.

**Comment by aait** [comment]
Fixed, conflict with "Fortnox integration for WooCommerce"
