### ISSUE TITLE
Not reporting VAT and correct description

### ISSUE THREAD

**Issue by webbverkstaden** [PayEx/PayEx.WooCommerce#78]
In the transaction reports at Payex merchant admin there are fields for description, VAT and VAT % that are not correctly filled out by the gateway. Also, the order ID is used for Product ID.

The VAT values ARE sent by the gateway, and are available via the order details view in payex admin, but for accounting reports to work in Payex they need be sent to these fields as well.

![screenshot-webbv-2019-03-26_145812](https://user-images.githubusercontent.com/25172186/55003205-3ad3cc80-4fd8-11e9-8ab8-69dbe076dd20.png)

**Comment by webbverkstaden** [comment]
![WC payex GW-screenshot-webbv-2019-03-26_145812](https://user-images.githubusercontent.com/25172186/55003811-5e4b4700-4fd9-11e9-9bc7-ad4a65b1cd59.png)

**Comment by aait** [comment]
There is a problem with Product ID and Product Description. The plugin is general (for many different merchant scenarios) and in many case the basket contains more than one product (and therefore more than one product ID and Product description). This is the solution that has been decided so far.

**Comment by aait** [comment]
For the missing VAT data in the transaction report in PayEx Merchant Admin, maybe @asbjornu could comment?

**Comment by asbjornu** [comment]
Thanks for the ping, @aait. I will have to ask internally why it's missing. I'll report back as soon as I have an answer.

**Comment by asbjornu** [comment]
VAT is initially set to `0` in the `Initialize` method:

https://github.com/PayEx/PayEx.WooCommerce/blob/master/includes/class-wc-gateway-payex-invoice.php#L389

Then VAT is set to the correct value in the `AddSingleOrderLine` method:

https://github.com/PayEx/PayEx.WooCommerce/blob/master/includes/class-wc-gateway-payex-invoice.php#L430

The VAT in the report is coming from `Initialize`, not from `AddSingleOrderLine`.

**Comment by aait** [comment]
@aait So should we make something solution for that?

**Comment by webbverkstaden** [comment]
Any plans for a solution to this?

**Comment by webbverkstaden** [comment]
@aait Excellent, many thanks.
